# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  server_config = release

else ifeq ($(config),debug)
  server_config = debug

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := server

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

server:
ifneq (,$(server_config))
	@echo "==== Building server ($(server_config)) ===="
	@${MAKE} --no-print-directory -C . -f server.make config=$(server_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f server.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   server"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"